### ISSUE TITLE
.checkApikey() wrong format

### ISSUE THREAD

**Issue by rgriffier** [yvoawk/getUMLS#2]
UMLS API Key is format :
```r
"^[:alnum:]{8}-[:alnum:]{4}-[:alnum:]{4}-[:alnum:]{4}-[:alnum:]{12}$"
```
Please change this in the .checkApikey() function

**Comment by yvoawk** [comment]
Thanks !

I changed it for the moment but I will have to check again because the old apikey don't follow this format.
